// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactDom from "react-dom";
import * as App$ReactTypescriptReasonTraining from "./components/App/App.bs.js";

var root = document.querySelector("#root");

if (!(root == null)) {
  ReactDom.render(React.createElement(App$ReactTypescriptReasonTraining.make, {}), root);
}

export {
  
}
/* root Not a pure module */
